modLoader="javafml"
loaderVersion="${mod_forge_version}"
license="All rights reserved"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/fakeblocks/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/fakeblocks.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/fakeblocks"
# logoFile="fakeblocks.png"
# credits=""
authors="${mod_vendor}"
description='''Fake Blocks'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"